// Generated by Haxe 4.0.0-rc.1+1fdd3d59b
(function () { "use strict";
var $estr = function() { return js_Boot.__string_rec(this,''); },$hxEnums = $hxEnums || {},$_;
function $extend(from, fields) {
	var proto = Object.create(from);
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var haxe_ds_List = function() {
	this.length = 0;
};
haxe_ds_List.__name__ = true;
haxe_ds_List.prototype = {
	add: function(item) {
		var x = new haxe_ds__$List_ListNode(item,null);
		if(this.h == null) {
			this.h = x;
		} else {
			this.q.next = x;
		}
		this.q = x;
		this.length++;
	}
	,remove: function(v) {
		var prev = null;
		var l = this.h;
		while(l != null) {
			if(l.item == v) {
				if(prev == null) {
					this.h = l.next;
				} else {
					prev.next = l.next;
				}
				if(this.q == l) {
					this.q = prev;
				}
				this.length--;
				return true;
			}
			prev = l;
			l = l.next;
		}
		return false;
	}
	,iterator: function() {
		return new haxe_ds__$List_ListIterator(this.h);
	}
};
var haxe_IMap = function() { };
haxe_IMap.__name__ = true;
var haxe_ds_IntMap = function() {
	this.h = { };
};
haxe_ds_IntMap.__name__ = true;
haxe_ds_IntMap.__interfaces__ = [haxe_IMap];
haxe_ds_IntMap.prototype = {
	remove: function(key) {
		if(!this.h.hasOwnProperty(key)) {
			return false;
		}
		delete(this.h[key]);
		return true;
	}
};
var echo_Echo = function() { };
echo_Echo.__name__ = true;
echo_Echo.regComponentContainer = function(cc) {
	echo_Echo.componentContainers.push(cc);
};
echo_Echo.toString = function() {
	var ret = "# ( " + echo_Echo.systems.length + " ) { " + echo_Echo.views.length + " } [ " + echo_Echo.entities.length + " ]";
	ret += " : " + echo_Echo.times.h[-2] + " ms";
	var _g_head = echo_Echo.systems.h;
	while(_g_head != null) {
		var val = _g_head.item;
		_g_head = _g_head.next;
		ret += "\n        (" + Std.string(val) + ") : " + echo_Echo.times.h[val.__id] + " ms";
	}
	var _g1_head = echo_Echo.views.h;
	while(_g1_head != null) {
		var val1 = _g1_head.item;
		_g1_head = _g1_head.next;
		ret += "\n    {" + Std.string(val1) + "} [" + val1.entities.length + "]";
	}
	return ret;
};
echo_Echo.update = function(dt) {
	var engineUpdateStartTimestamp = new Date().getTime();
	var _g_head = echo_Echo.systems.h;
	while(_g_head != null) {
		var val = _g_head.item;
		_g_head = _g_head.next;
		var systemUpdateStartTimestamp = new Date().getTime();
		val.update(dt);
		var this1 = echo_Echo.times;
		var key = val.__id;
		var value = new Date().getTime() - systemUpdateStartTimestamp | 0;
		this1.h[key] = value;
	}
	var this2 = echo_Echo.times;
	var value1 = new Date().getTime() - engineUpdateStartTimestamp | 0;
	this2.h[-2] = value1;
};
echo_Echo.addSystem = function(s) {
	if(!echo_Echo.systemsMap.h.hasOwnProperty(s.__id)) {
		echo_Echo.systemsMap.h[s.__id] = s;
		echo_Echo.systems.add(s);
		s.activate();
	}
};
echo_Echo.addView = function(v) {
	if(!echo_Echo.viewsMap.h.hasOwnProperty(v.__id)) {
		echo_Echo.viewsMap.h[v.__id] = v;
		echo_Echo.views.add(v);
	}
};
echo_Echo.id = function(immediate) {
	var id = ++echo_Echo.__componentSequence;
	if(immediate) {
		echo_Echo.entitiesMap.h[id] = id;
		echo_Echo.entities.add(id);
	}
	return id;
};
echo_Echo.remove = function(id) {
	if(echo_Echo.entitiesMap.h.hasOwnProperty(id)) {
		var _g_head = echo_Echo.views.h;
		while(_g_head != null) {
			var val = _g_head.item;
			_g_head = _g_head.next;
			val.removeIfMatch(id);
		}
		echo_Echo.entitiesMap.remove(id);
		echo_Echo.entities.remove(id);
	}
};
var ComponentContainer_$Example_$Animal = function() {
	this.components = echo_macro__$ComponentMacro_IntMapComponentContainer_$Impl_$._new();
	echo_Echo.regComponentContainer(this.components);
};
ComponentContainer_$Example_$Animal.__name__ = true;
ComponentContainer_$Example_$Animal.inst = function() {
	return ComponentContainer_$Example_$Animal.instance;
};
var ComponentContainer_$Example_$Position = function() {
	this.components = echo_macro__$ComponentMacro_IntMapComponentContainer_$Impl_$._new();
	echo_Echo.regComponentContainer(this.components);
};
ComponentContainer_$Example_$Position.__name__ = true;
ComponentContainer_$Example_$Position.inst = function() {
	return ComponentContainer_$Example_$Position.instance;
};
var ComponentContainer_$Example_$Sprite = function() {
	this.components = echo_macro__$ComponentMacro_IntMapComponentContainer_$Impl_$._new();
	echo_Echo.regComponentContainer(this.components);
};
ComponentContainer_$Example_$Sprite.__name__ = true;
ComponentContainer_$Example_$Sprite.inst = function() {
	return ComponentContainer_$Example_$Sprite.instance;
};
var ComponentContainer_$Example_$Timeout = function() {
	this.components = echo_macro__$ComponentMacro_IntMapComponentContainer_$Impl_$._new();
	echo_Echo.regComponentContainer(this.components);
};
ComponentContainer_$Example_$Timeout.__name__ = true;
ComponentContainer_$Example_$Timeout.inst = function() {
	return ComponentContainer_$Example_$Timeout.instance;
};
var ComponentContainer_$Example_$Velocity = function() {
	this.components = echo_macro__$ComponentMacro_IntMapComponentContainer_$Impl_$._new();
	echo_Echo.regComponentContainer(this.components);
};
ComponentContainer_$Example_$Velocity.__name__ = true;
ComponentContainer_$Example_$Velocity.inst = function() {
	return ComponentContainer_$Example_$Velocity.instance;
};
var Example = function() { };
Example.__name__ = true;
Example.main = function() {
	var canvas = window.document.createElement("code");
	var stat = window.document.createElement("pre");
	window.document.body.appendChild(canvas);
	window.document.body.appendChild(stat);
	var size = Std.parseInt(window.getComputedStyle(window.document.body).fontSize);
	var w = window.innerWidth / size > Example.MAX_WIDTH ? Example.MAX_WIDTH : Math.floor(window.innerWidth / size);
	var h = window.innerHeight / size > Example.MAX_HEIGHT ? Example.MAX_HEIGHT : Math.floor(window.innerHeight / size);
	echo_Echo.addSystem(new Movement(w,h));
	echo_Echo.addSystem(new Interaction());
	echo_Echo.addSystem(new Render(w,h,size,canvas));
	echo_Echo.addSystem(new InteractionEvent());
	var _g = 0;
	var _g1 = h;
	while(_g < _g1) {
		var y = _g++;
		var _g2 = 0;
		var _g11 = w;
		while(_g2 < _g11) {
			var x = _g2++;
			if(Math.random() > .5) {
				Example.grass(x,y);
			} else if(Math.random() > .2) {
				Example.tree(x,y);
			} else {
				Example.flower(x,y);
			}
		}
	}
	var _g21 = 0;
	var _g3 = Example.RABBITS_POPULATION;
	while(_g21 < _g3) {
		++_g21;
		Example.rabbit(Std.random(w),Std.random(h));
	}
	Example.tiger(Std.random(w),Std.random(h));
	window.setInterval(function() {
		echo_Echo.update(.050);
		stat.innerHTML = echo_Echo.toString();
	},50);
};
Example.grass = function(x,y) {
	var codes = ["&#x1F33E","&#x1F33F"];
	var id = echo_Echo.id(true);
	ComponentContainer_$Example_$Position.instance.components.h[id] = new Vec2(x,y);
	var _this = ComponentContainer_$Example_$Sprite.instance;
	var value = codes[Std.random(codes.length)];
	var this1 = window.document.createElement("span");
	this1.style.position = "absolute";
	this1.innerHTML = value;
	_this.components.h[id] = this1;
	if(echo_Echo.entitiesMap.h.hasOwnProperty(id)) {
		var _g_head = echo_Echo.views.h;
		while(_g_head != null) {
			var val = _g_head.item;
			_g_head = _g_head.next;
			val.addIfMatch(id);
		}
	}
};
Example.tree = function(x,y) {
	var codes = ["&#x1F332","&#x1F333"];
	var id = echo_Echo.id(true);
	ComponentContainer_$Example_$Position.instance.components.h[id] = new Vec2(x,y);
	var _this = ComponentContainer_$Example_$Sprite.instance;
	var value = codes[Std.random(codes.length)];
	var this1 = window.document.createElement("span");
	this1.style.position = "absolute";
	this1.innerHTML = value;
	_this.components.h[id] = this1;
	if(echo_Echo.entitiesMap.h.hasOwnProperty(id)) {
		var _g_head = echo_Echo.views.h;
		while(_g_head != null) {
			var val = _g_head.item;
			_g_head = _g_head.next;
			val.addIfMatch(id);
		}
	}
};
Example.flower = function(x,y) {
	var codes = ["&#x1F337","&#x1F339","&#x1F33B"];
	var id = echo_Echo.id(true);
	ComponentContainer_$Example_$Position.instance.components.h[id] = new Vec2(x,y);
	var _this = ComponentContainer_$Example_$Sprite.instance;
	var value = codes[Std.random(codes.length)];
	var this1 = window.document.createElement("span");
	this1.style.position = "absolute";
	this1.innerHTML = value;
	_this.components.h[id] = this1;
	if(echo_Echo.entitiesMap.h.hasOwnProperty(id)) {
		var _g_head = echo_Echo.views.h;
		while(_g_head != null) {
			var val = _g_head.item;
			_g_head = _g_head.next;
			val.addIfMatch(id);
		}
	}
};
Example.rabbit = function(x,y) {
	var this1 = new Vec2(x,y);
	var vel = Example.randomVelocity(1);
	var this2 = window.document.createElement("span");
	this2.style.position = "absolute";
	this2.innerHTML = "&#x1F407;";
	var id = echo_Echo.id(true);
	ComponentContainer_$Example_$Position.instance.components.h[id] = this1;
	ComponentContainer_$Example_$Velocity.instance.components.h[id] = vel;
	ComponentContainer_$Example_$Sprite.instance.components.h[id] = this2;
	ComponentContainer_$Example_$Animal.instance.components.h[id] = Animal.Rabbit;
	if(echo_Echo.entitiesMap.h.hasOwnProperty(id)) {
		var _g_head = echo_Echo.views.h;
		while(_g_head != null) {
			var val = _g_head.item;
			_g_head = _g_head.next;
			val.addIfMatch(id);
		}
	}
};
Example.tiger = function(x,y) {
	var this1 = new Vec2(x,y);
	var vel = Example.randomVelocity(10);
	var this2 = window.document.createElement("span");
	this2.style.position = "absolute";
	this2.innerHTML = "&#x1F405;";
	var spr = this2;
	spr.style.fontSize = "200%";
	var id = echo_Echo.id(true);
	ComponentContainer_$Example_$Position.instance.components.h[id] = this1;
	ComponentContainer_$Example_$Velocity.instance.components.h[id] = vel;
	ComponentContainer_$Example_$Sprite.instance.components.h[id] = spr;
	ComponentContainer_$Example_$Animal.instance.components.h[id] = Animal.Tiger;
	if(echo_Echo.entitiesMap.h.hasOwnProperty(id)) {
		var _g_head = echo_Echo.views.h;
		while(_g_head != null) {
			var val = _g_head.item;
			_g_head = _g_head.next;
			val.addIfMatch(id);
		}
	}
};
Example.event = function(x,y,type) {
	var code;
	switch(type) {
	case "heart":
		code = "&#x1F498;";
		break;
	case "skull":
		code = "&#x1F480;";
		break;
	default:
		code = "";
	}
	var id = echo_Echo.id(true);
	ComponentContainer_$Example_$Position.instance.components.h[id] = new Vec2(x,y);
	var _this = ComponentContainer_$Example_$Sprite.instance;
	var this1 = window.document.createElement("span");
	this1.style.position = "absolute";
	this1.innerHTML = code;
	_this.components.h[id] = this1;
	ComponentContainer_$Example_$Timeout.instance.components.h[id] = new Timeout(3.0);
	if(echo_Echo.entitiesMap.h.hasOwnProperty(id)) {
		var _g_head = echo_Echo.views.h;
		while(_g_head != null) {
			var val = _g_head.item;
			_g_head = _g_head.next;
			val.addIfMatch(id);
		}
	}
};
Example.randomVelocity = function(speed) {
	var d = Math.random() * Math.PI * 2;
	return new Vec2(Math.cos(d) * speed,Math.sin(d) * speed);
};
var Vec2 = function(x,y) {
	this.x = x != null ? x : .0;
	this.y = y != null ? y : .0;
};
Vec2.__name__ = true;
var Animal = $hxEnums["Animal"] = { __ename__ : true, __constructs__ : ["Rabbit","Tiger"]
	,Rabbit: {_hx_index:0,__enum__:"Animal",toString:$estr}
	,Tiger: {_hx_index:1,__enum__:"Animal",toString:$estr}
};
var Timeout = function(t) {
	this.t = this.timeout = t;
};
Timeout.__name__ = true;
var echo_System = function() {
	this.__id = -1;
};
echo_System.__name__ = true;
echo_System.prototype = {
	activate: function() {
	}
	,update: function(dt) {
	}
	,toString: function() {
		return "System";
	}
};
var Movement = function(w,h) {
	echo_System.call(this);
	this.__id = 4;
	this.w = w;
	this.h = h;
};
Movement.__name__ = true;
Movement.__super__ = echo_System;
Movement.prototype = $extend(echo_System.prototype,{
	update: function(dt) {
		var _gthis = this;
		var _this = this.bodies;
		var _g_head = _this.entities.h;
		while(_g_head != null) {
			var val = _g_head.item;
			_g_head = _g_head.next;
			var pos = _this.position.components.h[val];
			var vel = _this.velocity.components.h[val];
			pos.x += vel.x * dt;
			pos.y += vel.y * dt;
			if(pos.x >= _gthis.w) {
				pos.x -= _gthis.w;
			}
			if(pos.x < 0) {
				pos.x += _gthis.w;
			}
			if(pos.y >= _gthis.h) {
				pos.y -= _gthis.h;
			}
			if(pos.y < 0) {
				pos.y += _gthis.h;
			}
		}
	}
	,activate: function() {
		this.bodies = View_$Example_$Position_$Example_$Velocity.instance;
		this.bodies.activate();
	}
	,toString: function() {
		return "Example.Movement";
	}
});
var Render = function(w,h,size,canvas) {
	echo_System.call(this);
	this.__id = 3;
	this.world = [];
	var _g = 0;
	while(_g < h) {
		var y = _g++;
		this.world[y] = [];
		var _g1 = 0;
		while(_g1 < w) {
			var x = _g1++;
			var span = window.document.createElement("span");
			span.style.position = "absolute";
			span.style.left = "" + x * size + "px";
			span.style.top = "" + y * size + "px";
			this.world[y][x] = span;
			canvas.appendChild(span);
		}
		canvas.appendChild(window.document.createElement("br"));
	}
};
Render.__name__ = true;
Render.__super__ = echo_System;
Render.prototype = $extend(echo_System.prototype,{
	update: function(dt) {
		var _gthis = this;
		var _this = this.view_example_position_example_sprite_example_velocity;
		var _g_head = _this.entities.h;
		while(_g_head != null) {
			var val = _g_head.item;
			_g_head = _g_head.next;
			var pos = _this.position.components.h[val];
			_gthis.world[pos.y | 0][pos.x | 0].appendChild(_this.sprite.components.h[val]);
		}
	}
	,activate: function() {
		var _gthis = this;
		this.__appendVisual = function(id,pos,spr) {
			_gthis.world[pos.y | 0][pos.x | 0].appendChild(spr);
		};
		this.__removeVisual = function(id1,position,sprite) {
			ComponentContainer_$Example_$Sprite.instance.components.h[id1].remove();
		};
		this.visuals = View_$Example_$Position_$Example_$Sprite.instance;
		this.visuals.activate();
		this.view_example_position_example_sprite_example_velocity = View_$Example_$Position_$Example_$Sprite_$Example_$Velocity.instance;
		this.view_example_position_example_sprite_example_velocity.activate();
		this.visuals.onAdded.push(this.__appendVisual);
		this.visuals.onRemoved.push(this.__removeVisual);
		var _this = this.visuals;
		var _g_head = _this.entities.h;
		while(_g_head != null) {
			var val = _g_head.item;
			_g_head = _g_head.next;
			var pos1 = _this.position.components.h[val];
			_gthis.world[pos1.y | 0][pos1.x | 0].appendChild(_this.sprite.components.h[val]);
		}
	}
	,toString: function() {
		return "Example.Render";
	}
});
var Interaction = function() {
	echo_System.call(this);
	this.__id = 2;
};
Interaction.__name__ = true;
Interaction.__super__ = echo_System;
Interaction.prototype = $extend(echo_System.prototype,{
	update: function(dt) {
		var _gthis = this;
		var del = [];
		var _this = this.animals;
		var _g_head = _this.entities.h;
		while(_g_head != null) {
			var val = _g_head.item;
			_g_head = _g_head.next;
			var a1 = _this.animal.components.h[val];
			var pos1 = _this.position.components.h[val];
			var _this1 = _gthis.animals;
			var _g_head1 = _this1.entities.h;
			while(_g_head1 != null) {
				var val1 = _g_head1.item;
				_g_head1 = _g_head1.next;
				var a2 = _this1.animal.components.h[val1];
				if(val != val1 && _gthis.isInteract(pos1,_this1.position.components.h[val1],1.0)) {
					if(a1 == Animal.Tiger && a2 == Animal.Rabbit) {
						console.log("test/Example.hx:235:","eat " + val1);
						Example.event(pos1.x,pos1.y,"skull");
						del.push(val1);
					}
					if(a1 == Animal.Rabbit && a2 == Animal.Rabbit) {
						if(Lambda.count(_gthis.animals.entities,function(i) {
							return ComponentContainer_$Example_$Animal.instance.components.h[i] == Animal.Rabbit;
						}) < Example.RABBITS_POPULATION) {
							Example.rabbit(pos1.x,pos1.y);
							Example.event(pos1.x,pos1.y,"heart");
						}
					}
				}
			}
		}
		var _g = 0;
		while(_g < del.length) echo__$Entity_Entity_$Impl_$.destroy(del[_g++]);
	}
	,isInteract: function(pos1,pos2,radius) {
		if(Math.abs(pos1.x - pos2.x) < radius) {
			return Math.abs(pos1.y - pos2.y) < radius;
		} else {
			return false;
		}
	}
	,activate: function() {
		this.animals = View_$Example_$Animal_$Example_$Position.instance;
		this.animals.activate();
	}
	,toString: function() {
		return "Example.Interaction";
	}
});
var InteractionEvent = function() {
	echo_System.call(this);
	this.__id = 1;
};
InteractionEvent.__name__ = true;
InteractionEvent.__super__ = echo_System;
InteractionEvent.prototype = $extend(echo_System.prototype,{
	update: function(dt) {
		var _this = this.view_example_sprite_example_timeout;
		var _g_head = _this.entities.h;
		while(_g_head != null) {
			var val = _g_head.item;
			_g_head = _g_head.next;
			var t = _this.timeout.components.h[val];
			var s = _this.sprite.components.h[val];
			s.style.opacity = "" + t.t / t.timeout;
			t.t -= dt;
			if(t.t <= .0) {
				s.style.opacity = ".0";
				echo__$Entity_Entity_$Impl_$.destroy(val);
			}
		}
	}
	,activate: function() {
		this.view_example_sprite_example_timeout = View_$Example_$Sprite_$Example_$Timeout.instance;
		this.view_example_sprite_example_timeout.activate();
	}
	,toString: function() {
		return "Example.InteractionEvent";
	}
});
var HxOverrides = function() { };
HxOverrides.__name__ = true;
HxOverrides.iter = function(a) {
	return { cur : 0, arr : a, hasNext : function() {
		return this.cur < this.arr.length;
	}, next : function() {
		return this.arr[this.cur++];
	}};
};
var Lambda = function() { };
Lambda.__name__ = true;
Lambda.count = function(it,pred) {
	var n = 0;
	if(pred == null) {
		var _ = $getIterator(it);
		while(_.hasNext()) {
			_.next();
			++n;
		}
	} else {
		var x = $getIterator(it);
		while(x.hasNext()) if(pred(x.next())) {
			++n;
		}
	}
	return n;
};
Math.__name__ = true;
var Std = function() { };
Std.__name__ = true;
Std.string = function(s) {
	return js_Boot.__string_rec(s,"");
};
Std.parseInt = function(x) {
	var v = parseInt(x, x && x[0]=="0" && (x[1]=="x" || x[1]=="X") ? 16 : 10);
	if(isNaN(v)) {
		return null;
	}
	return v;
};
Std.random = function(x) {
	if(x <= 0) {
		return 0;
	} else {
		return Math.floor(Math.random() * x);
	}
};
var echo_ViewBase = function() {
	this.entities = new haxe_ds_List();
	this.__id = -1;
	this.entitiesMap = new haxe_ds_IntMap();
};
echo_ViewBase.__name__ = true;
echo_ViewBase.prototype = {
	activate: function() {
		echo_Echo.addView(this);
		var _g_head = echo_Echo.entities.h;
		while(_g_head != null) {
			var val = _g_head.item;
			_g_head = _g_head.next;
			this.addIfMatch(val);
		}
	}
	,isMatch: function(id) {
		return false;
	}
	,add: function(id) {
		this.entitiesMap.h[id] = id;
		this.entities.add(id);
	}
	,remove: function(id) {
		this.entities.remove(id);
		this.entitiesMap.remove(id);
	}
	,addIfMatch: function(id) {
		if(!this.entitiesMap.h.hasOwnProperty(id) && this.isMatch(id)) {
			this.add(id);
		}
	}
	,removeIfMatch: function(id) {
		if(this.entitiesMap.h.hasOwnProperty(id)) {
			this.remove(id);
		}
	}
	,toString: function() {
		return "ViewBase";
	}
};
var View_$Example_$Animal_$Example_$Position = function() {
	this.onRemoved = [];
	this.onAdded = [];
	echo_ViewBase.call(this);
	this.__id = 1;
	this.activate();
};
View_$Example_$Animal_$Example_$Position.__name__ = true;
View_$Example_$Animal_$Example_$Position.inst = function() {
	return View_$Example_$Animal_$Example_$Position.instance;
};
View_$Example_$Animal_$Example_$Position.__super__ = echo_ViewBase;
View_$Example_$Animal_$Example_$Position.prototype = $extend(echo_ViewBase.prototype,{
	add: function(id) {
		echo_ViewBase.prototype.add.call(this,id);
		var i = 0;
		var l = this.onAdded.length;
		while(i < l) {
			var listener = this.onAdded[i];
			if(listener != null) {
				listener(id,this.animal.components.h[id],this.position.components.h[id]);
				++i;
			} else {
				this.onAdded.splice(i,1);
				--l;
			}
		}
	}
	,remove: function(id) {
		var i = 0;
		var l = this.onRemoved.length;
		while(i < l) {
			var listener = this.onRemoved[i];
			if(listener != null) {
				listener(id,this.animal.components.h[id],this.position.components.h[id]);
				++i;
			} else {
				this.onRemoved.splice(i,1);
				--l;
			}
		}
		echo_ViewBase.prototype.remove.call(this,id);
	}
	,activate: function() {
		this.animal = ComponentContainer_$Example_$Animal.instance;
		this.position = ComponentContainer_$Example_$Position.instance;
		echo_ViewBase.prototype.activate.call(this);
	}
	,isMatch: function(id) {
		if(this.animal.components.h[id] != null) {
			return this.position.components.h[id] != null;
		} else {
			return false;
		}
	}
	,toString: function() {
		return "Example.Animal,Example.Position";
	}
});
var View_$Example_$Position_$Example_$Sprite = function() {
	this.onRemoved = [];
	this.onAdded = [];
	echo_ViewBase.call(this);
	this.__id = 2;
	this.activate();
};
View_$Example_$Position_$Example_$Sprite.__name__ = true;
View_$Example_$Position_$Example_$Sprite.inst = function() {
	return View_$Example_$Position_$Example_$Sprite.instance;
};
View_$Example_$Position_$Example_$Sprite.__super__ = echo_ViewBase;
View_$Example_$Position_$Example_$Sprite.prototype = $extend(echo_ViewBase.prototype,{
	add: function(id) {
		echo_ViewBase.prototype.add.call(this,id);
		var i = 0;
		var l = this.onAdded.length;
		while(i < l) {
			var listener = this.onAdded[i];
			if(listener != null) {
				listener(id,this.position.components.h[id],this.sprite.components.h[id]);
				++i;
			} else {
				this.onAdded.splice(i,1);
				--l;
			}
		}
	}
	,remove: function(id) {
		var i = 0;
		var l = this.onRemoved.length;
		while(i < l) {
			var listener = this.onRemoved[i];
			if(listener != null) {
				listener(id,this.position.components.h[id],this.sprite.components.h[id]);
				++i;
			} else {
				this.onRemoved.splice(i,1);
				--l;
			}
		}
		echo_ViewBase.prototype.remove.call(this,id);
	}
	,activate: function() {
		this.position = ComponentContainer_$Example_$Position.instance;
		this.sprite = ComponentContainer_$Example_$Sprite.instance;
		echo_ViewBase.prototype.activate.call(this);
	}
	,isMatch: function(id) {
		if(this.position.components.h[id] != null) {
			return this.sprite.components.h[id] != null;
		} else {
			return false;
		}
	}
	,toString: function() {
		return "Example.Position,Example.Sprite";
	}
});
var View_$Example_$Position_$Example_$Sprite_$Example_$Velocity = function() {
	this.onRemoved = [];
	this.onAdded = [];
	echo_ViewBase.call(this);
	this.__id = 4;
	this.activate();
};
View_$Example_$Position_$Example_$Sprite_$Example_$Velocity.__name__ = true;
View_$Example_$Position_$Example_$Sprite_$Example_$Velocity.inst = function() {
	return View_$Example_$Position_$Example_$Sprite_$Example_$Velocity.instance;
};
View_$Example_$Position_$Example_$Sprite_$Example_$Velocity.__super__ = echo_ViewBase;
View_$Example_$Position_$Example_$Sprite_$Example_$Velocity.prototype = $extend(echo_ViewBase.prototype,{
	add: function(id) {
		echo_ViewBase.prototype.add.call(this,id);
		var i = 0;
		var l = this.onAdded.length;
		while(i < l) {
			var listener = this.onAdded[i];
			if(listener != null) {
				listener(id,this.velocity.components.h[id],this.position.components.h[id],this.sprite.components.h[id]);
				++i;
			} else {
				this.onAdded.splice(i,1);
				--l;
			}
		}
	}
	,remove: function(id) {
		var i = 0;
		var l = this.onRemoved.length;
		while(i < l) {
			var listener = this.onRemoved[i];
			if(listener != null) {
				listener(id,this.velocity.components.h[id],this.position.components.h[id],this.sprite.components.h[id]);
				++i;
			} else {
				this.onRemoved.splice(i,1);
				--l;
			}
		}
		echo_ViewBase.prototype.remove.call(this,id);
	}
	,activate: function() {
		this.velocity = ComponentContainer_$Example_$Velocity.instance;
		this.position = ComponentContainer_$Example_$Position.instance;
		this.sprite = ComponentContainer_$Example_$Sprite.instance;
		echo_ViewBase.prototype.activate.call(this);
	}
	,isMatch: function(id) {
		if(this.velocity.components.h[id] != null && this.position.components.h[id] != null) {
			return this.sprite.components.h[id] != null;
		} else {
			return false;
		}
	}
	,toString: function() {
		return "Example.Position,Example.Sprite,Example.Velocity";
	}
});
var View_$Example_$Position_$Example_$Velocity = function() {
	this.onRemoved = [];
	this.onAdded = [];
	echo_ViewBase.call(this);
	this.__id = 3;
	this.activate();
};
View_$Example_$Position_$Example_$Velocity.__name__ = true;
View_$Example_$Position_$Example_$Velocity.inst = function() {
	return View_$Example_$Position_$Example_$Velocity.instance;
};
View_$Example_$Position_$Example_$Velocity.__super__ = echo_ViewBase;
View_$Example_$Position_$Example_$Velocity.prototype = $extend(echo_ViewBase.prototype,{
	add: function(id) {
		echo_ViewBase.prototype.add.call(this,id);
		var i = 0;
		var l = this.onAdded.length;
		while(i < l) {
			var listener = this.onAdded[i];
			if(listener != null) {
				listener(id,this.position.components.h[id],this.velocity.components.h[id]);
				++i;
			} else {
				this.onAdded.splice(i,1);
				--l;
			}
		}
	}
	,remove: function(id) {
		var i = 0;
		var l = this.onRemoved.length;
		while(i < l) {
			var listener = this.onRemoved[i];
			if(listener != null) {
				listener(id,this.position.components.h[id],this.velocity.components.h[id]);
				++i;
			} else {
				this.onRemoved.splice(i,1);
				--l;
			}
		}
		echo_ViewBase.prototype.remove.call(this,id);
	}
	,activate: function() {
		this.position = ComponentContainer_$Example_$Position.instance;
		this.velocity = ComponentContainer_$Example_$Velocity.instance;
		echo_ViewBase.prototype.activate.call(this);
	}
	,isMatch: function(id) {
		if(this.position.components.h[id] != null) {
			return this.velocity.components.h[id] != null;
		} else {
			return false;
		}
	}
	,toString: function() {
		return "Example.Position,Example.Velocity";
	}
});
var View_$Example_$Sprite_$Example_$Timeout = function() {
	this.onRemoved = [];
	this.onAdded = [];
	echo_ViewBase.call(this);
	this.__id = 0;
	this.activate();
};
View_$Example_$Sprite_$Example_$Timeout.__name__ = true;
View_$Example_$Sprite_$Example_$Timeout.inst = function() {
	return View_$Example_$Sprite_$Example_$Timeout.instance;
};
View_$Example_$Sprite_$Example_$Timeout.__super__ = echo_ViewBase;
View_$Example_$Sprite_$Example_$Timeout.prototype = $extend(echo_ViewBase.prototype,{
	add: function(id) {
		echo_ViewBase.prototype.add.call(this,id);
		var i = 0;
		var l = this.onAdded.length;
		while(i < l) {
			var listener = this.onAdded[i];
			if(listener != null) {
				listener(id,this.timeout.components.h[id],this.sprite.components.h[id]);
				++i;
			} else {
				this.onAdded.splice(i,1);
				--l;
			}
		}
	}
	,remove: function(id) {
		var i = 0;
		var l = this.onRemoved.length;
		while(i < l) {
			var listener = this.onRemoved[i];
			if(listener != null) {
				listener(id,this.timeout.components.h[id],this.sprite.components.h[id]);
				++i;
			} else {
				this.onRemoved.splice(i,1);
				--l;
			}
		}
		echo_ViewBase.prototype.remove.call(this,id);
	}
	,activate: function() {
		this.timeout = ComponentContainer_$Example_$Timeout.instance;
		this.sprite = ComponentContainer_$Example_$Sprite.instance;
		echo_ViewBase.prototype.activate.call(this);
	}
	,isMatch: function(id) {
		if(this.timeout.components.h[id] != null) {
			return this.sprite.components.h[id] != null;
		} else {
			return false;
		}
	}
	,toString: function() {
		return "Example.Sprite,Example.Timeout";
	}
});
var echo__$Entity_Entity_$Impl_$ = {};
echo__$Entity_Entity_$Impl_$.__name__ = true;
echo__$Entity_Entity_$Impl_$.removeAll = function(this1) {
	var _g = 0;
	var _g1 = echo_Echo.componentContainers;
	while(_g < _g1.length) _g1[_g++].remove(this1);
};
echo__$Entity_Entity_$Impl_$.destroy = function(this1) {
	echo_Echo.remove(this1);
	echo__$Entity_Entity_$Impl_$.removeAll(this1);
};
var echo_macro__$ComponentMacro_IntMapComponentContainer_$Impl_$ = {};
echo_macro__$ComponentMacro_IntMapComponentContainer_$Impl_$.__name__ = true;
echo_macro__$ComponentMacro_IntMapComponentContainer_$Impl_$._new = function() {
	return new haxe_ds_IntMap();
};
var haxe_ds__$List_ListNode = function(item,next) {
	this.item = item;
	this.next = next;
};
haxe_ds__$List_ListNode.__name__ = true;
var haxe_ds__$List_ListIterator = function(head) {
	this.head = head;
};
haxe_ds__$List_ListIterator.__name__ = true;
haxe_ds__$List_ListIterator.prototype = {
	hasNext: function() {
		return this.head != null;
	}
	,next: function() {
		var val = this.head.item;
		this.head = this.head.next;
		return val;
	}
};
var js__$Boot_HaxeError = function(val) {
	Error.call(this);
	this.val = val;
	if(Error.captureStackTrace) {
		Error.captureStackTrace(this,js__$Boot_HaxeError);
	}
};
js__$Boot_HaxeError.__name__ = true;
js__$Boot_HaxeError.__super__ = Error;
js__$Boot_HaxeError.prototype = $extend(Error.prototype,{
});
var js_Boot = function() { };
js_Boot.__name__ = true;
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(o.__enum__) {
			var e = $hxEnums[o.__enum__];
			var n = e.__constructs__[o._hx_index];
			var con = e[n];
			if(con.__params__) {
				s += "\t";
				var tmp = n + "(";
				var _g = [];
				var _g1 = 0;
				var _g2 = con.__params__;
				while(_g1 < _g2.length) {
					var p = _g2[_g1];
					++_g1;
					_g.push(js_Boot.__string_rec(o[p],s));
				}
				return tmp + _g.join(",") + ")";
			} else {
				return n;
			}
		}
		if(((o) instanceof Array)) {
			var l = o.length;
			var i;
			var str = "[";
			s += "\t";
			var _g3 = 0;
			var _g11 = l;
			while(_g3 < _g11) {
				var i1 = _g3++;
				str += (i1 > 0 ? "," : "") + js_Boot.__string_rec(o[i1],s);
			}
			str += "]";
			return str;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( e1 ) {
			var e2 = ((e1) instanceof js__$Boot_HaxeError) ? e1.val : e1;
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var k = null;
		var str1 = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		for( var k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str1.length != 2) {
			str1 += ", \n";
		}
		str1 += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str1 += "\n" + s + "}";
		return str1;
	case "string":
		return o;
	default:
		return String(o);
	}
};
function $getIterator(o) { if( o instanceof Array ) return HxOverrides.iter(o); else return o.iterator(); }
String.__name__ = true;
Array.__name__ = true;
Date.__name__ = "Date";
Object.defineProperty(js__$Boot_HaxeError.prototype,"message",{ get : function() {
	return String(this.val);
}});
echo_Echo.__componentSequence = -1;
echo_Echo.componentContainers = [];
echo_Echo.entitiesMap = new haxe_ds_IntMap();
echo_Echo.viewsMap = new haxe_ds_IntMap();
echo_Echo.systemsMap = new haxe_ds_IntMap();
echo_Echo.entities = new haxe_ds_List();
echo_Echo.views = new haxe_ds_List();
echo_Echo.systems = new haxe_ds_List();
echo_Echo.times = new haxe_ds_IntMap();
ComponentContainer_$Example_$Animal.instance = new ComponentContainer_$Example_$Animal();
ComponentContainer_$Example_$Position.instance = new ComponentContainer_$Example_$Position();
ComponentContainer_$Example_$Sprite.instance = new ComponentContainer_$Example_$Sprite();
ComponentContainer_$Example_$Timeout.instance = new ComponentContainer_$Example_$Timeout();
ComponentContainer_$Example_$Velocity.instance = new ComponentContainer_$Example_$Velocity();
Example.RABBITS_POPULATION = 64;
Example.MAX_WIDTH = 60;
Example.MAX_HEIGHT = 40;
View_$Example_$Animal_$Example_$Position.instance = new View_$Example_$Animal_$Example_$Position();
View_$Example_$Position_$Example_$Sprite.instance = new View_$Example_$Position_$Example_$Sprite();
View_$Example_$Position_$Example_$Sprite_$Example_$Velocity.instance = new View_$Example_$Position_$Example_$Sprite_$Example_$Velocity();
View_$Example_$Position_$Example_$Velocity.instance = new View_$Example_$Position_$Example_$Velocity();
View_$Example_$Sprite_$Example_$Timeout.instance = new View_$Example_$Sprite_$Example_$Timeout();
Example.main();
})();
